/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.6
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package decentro.tech.client.api;

import decentro.tech.client.ApiException;
import decentro.tech.client.ApiClient;
import decentro.tech.client.ApiException;
import decentro.tech.client.Configuration;
import java.time.OffsetDateTime;
import decentro.tech.client.model.User;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.BeforeClass;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private static UserApi api;

    
    @BeforeClass
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new UserApi(apiClient);
    }

    /**
     * Create user
     *
     * This can only be done by the logged in user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        User user = null;
        api.createUser(user)
                .execute();
        // TODO: test validations
    }

    /**
     * Creates list of users with given input array
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUsersWithArrayInputTest() throws ApiException {
        List<User> user = null;
        api.createUsersWithArrayInput(user)
                .execute();
        // TODO: test validations
    }

    /**
     * Creates list of users with given input array
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUsersWithListInputTest() throws ApiException {
        List<User> user = null;
        api.createUsersWithListInput(user)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete user
     *
     * This can only be done by the logged in user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String username = null;
        api.deleteUser(username)
                .execute();
        // TODO: test validations
    }

    /**
     * Get user by user name
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByNameTest() throws ApiException {
        String username = null;
        User response = api.getUserByName(username)
                .execute();
        // TODO: test validations
    }

    /**
     * Logs user into the system
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginUserTest() throws ApiException {
        String username = null;
        String password = null;
        String response = api.loginUser(username, password)
                .execute();
        // TODO: test validations
    }

    /**
     * Logs out current logged in user session
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void logoutUserTest() throws ApiException {
        api.logoutUser()
                .execute();
        // TODO: test validations
    }

    /**
     * Updated user
     *
     * This can only be done by the logged in user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        String username = null;
        User user = null;
        api.updateUser(username, user)
                .execute();
        // TODO: test validations
    }

}
